### ISSUE TITLE
Improve producer serialization schema 

### ISSUE THREAD

**Issue by VenturaDelMonte** [0xNacho/KafkaConsumerProducer#19]
The current serialization mechanism transforms each object to a string and then to json. This is an expensive process in term of overhead and network transfer not only on the kafka side but also on the flink side. Therefore, I would suggest to improve the schema as follows:

Data Item | Data Type | Size | Node
------------ | -------------| -------------| -------------
MAGIC NUMBER | Int | 4 bytes |
Coil Type | Byte | 1 byte | 1D or 2D
Coil Id | Int | 4 bytes |
X position | Double | 8 bytes |
Y position | Double | 8 bytes | only 2D coils
Variable Id | Int | 4 bytes | C00xx
Value | Double | 8 bytes |

I would suggest to use a kryo serializer to this end. Of course, this change will be reflected on the Flink side as well.

**Comment by 0xNacho** [comment]
This feature is almost ready. Just a basic question (and sorry for ignorance, i've never worked with magic numbers): which is the value of the MAGIC NUMBER field for each row? @VenturaDelMonte

**Comment by 0xNacho** [comment]
I'm working with an optimised version of the previous table:

Data Item | Data Type | Size | Node
------------ | -------------| -------------| -------------
MAGIC NUMBER | Int | 4 bytes |
Coil Id | Int | 4 bytes |
X position | Double | 8 bytes |
Y position | Double | 8 bytes | only 2D coils
Variable Id | Int | 4 bytes | C00xx
Value | Double | 8 bytes |


I just removed the coil type parameter, since it is redundant (when you have the Y position you know that this is a 2D variable. Otherwise, it is 1D).

**Comment by VenturaDelMonte** [comment]
Can't wait to test this new feature! Regarding the MAGIC NUMBER, it may be any numerical constant as long as it is the same on both side (kakfa job and flink job). It will be used as a sort of versioning control. I would suggest to use 0x00687691 (which is basically the PROTEUS EU id written as an hex number :D ).
However, I know that coil type is redundant but this is the only way to know the type of the coil, because we are gonna serialize everything through Kryo::writeObject, thus no class metadata. Sorry I should have explained it better. Please, have a look at [this UT ](https://github.com/VenturaDelMonte/proteus-job/blob/f86bcd46013b1aab460aad7a506ea097879414a5/src/main/scala/eu/proteus/job/operations/serializer/CoilMeasurementKryoSerializer.scala) in my PR on the Flink Job. Perhaps, [this example](https://github.com/nielsutrecht/kafka-serializer-example/blob/master/src/main/java/com/nibado/example/kafka/serialization/KryoReadingSerializer.java) could also you help. However, if you have further questions, please free to ask :)

**Comment by 0xNacho** [comment]
Thanks @VenturaDelMonte ! You are right. I was thinking of it just after posting my comment :D
